package review

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// LLMClient is an interface for LLM interactions.
// This allows decoupling from the agent package.
type LLMClient interface {
	Chat(prompt string) (string, error)
}

// AIInsight represents an insight from AI analysis.
type AIInsight struct {
	Severity    string  `json:"severity"`    // critical, warning, info
	Category    string  `json:"category"`    // security, performance, bug, readability
	Line        int     `json:"line"`        // 1-indexed line number
	Description string  `json:"description"` // Problem description
	Suggestion  string  `json:"suggestion"`  // Fix suggestion
	Confidence  float64 `json:"confidence"`  // 0.0-1.0
}

// AIAnalysisResult represents the full AI analysis response.
type AIAnalysisResult struct {
	Insights []AIInsight `json:"insights"`
}

// AIFixResult represents an AI-generated fix.
type AIFixResult struct {
	OldCode string `json:"old_code"`
	NewCode string `json:"new_code"`
}

// AIAnalyzer performs AI-based code analysis.
type AIAnalyzer struct {
	LLM LLMClient
}

// NewAIAnalyzer creates a new AI analyzer.
func NewAIAnalyzer(llm LLMClient) *AIAnalyzer {
	return &AIAnalyzer{LLM: llm}
}

// AnalyzeWithAI analyzes code using LLM and returns insights.
func (a *AIAnalyzer) AnalyzeWithAI(code string, filePath string) ([]AIInsight, error) {
	if a.LLM == nil {
		return nil, fmt.Errorf("LLM client not configured")
	}

	prompt := buildAnalysisPrompt(code, filePath)
	response, err := a.LLM.Chat(prompt)
	if err != nil {
		return nil, fmt.Errorf("LLM call failed: %w", err)
	}

	result, err := parseAnalysisResponse(response)
	if err != nil {
		return nil, fmt.Errorf("failed to parse AI response: %w", err)
	}

	return result.Insights, nil
}

// GenerateAIFix generates a fix proposal using LLM.
func (a *AIAnalyzer) GenerateAIFix(issue Issue, code string) (*FixProposal, error) {
	if a.LLM == nil {
		return nil, fmt.Errorf("LLM client not configured")
	}

	prompt := buildFixPrompt(issue, code)
	response, err := a.LLM.Chat(prompt)
	if err != nil {
		return nil, fmt.Errorf("LLM call failed: %w", err)
	}

	fixResult, err := parseFixResponse(response)
	if err != nil {
		return nil, fmt.Errorf("failed to parse fix response: %w", err)
	}

	if fixResult.OldCode == "" || fixResult.NewCode == "" {
		return nil, fmt.Errorf("AI did not generate a valid fix")
	}

	// Verify old_code exists in the source
	if !strings.Contains(code, fixResult.OldCode) {
		return nil, fmt.Errorf("AI generated old_code not found in source")
	}

	return &FixProposal{
		IssueID:    issue.ID,
		Title:      fmt.Sprintf("AI Fix: %s", issue.Title),
		Rationale:  "Generated by AI based on code analysis",
		Example:    fixResult.NewCode,
		FilePath:   issue.Path,
		OldCode:    fixResult.OldCode,
		NewCode:    fixResult.NewCode,
		Actionable: true,
		Notes:      []string{"AI-generated fix - please review carefully"},
	}, nil
}

func buildAnalysisPrompt(code string, filePath string) string {
	lang := detectLanguage(filePath)
	return fmt.Sprintf(`Analyze the following code and identify potential issues.
File: %s
Language: %s

%s%s%s

Analyze for:
- Security vulnerabilities (injection, exposure, weak crypto)
- Performance issues (inefficient algorithms, memory leaks)
- Potential bugs (nil dereference, race conditions, off-by-one)
- Readability and maintainability issues

Output JSON only (no markdown, no explanation):
{
  "insights": [
    {
      "severity": "critical|warning|info",
      "category": "security|performance|bug|readability",
      "line": 123,
      "description": "Problem description",
      "suggestion": "How to fix",
      "confidence": 0.95
    }
  ]
}

If no issues found, return: {"insights": []}`, filePath, lang, "```"+lang+"\n", code, "\n```")
}

func buildFixPrompt(issue Issue, code string) string {
	return fmt.Sprintf(`Generate a fix for the following issue.

Issue:
- File: %s
- Line: %d
- Title: %s
- Description: %s

Current code:
%s%s%s

Generate the minimal code change needed to fix this issue.
Output JSON only (no markdown, no explanation):
{
  "old_code": "exact code to replace (copy from above)",
  "new_code": "fixed code"
}

IMPORTANT:
- old_code must be an exact substring from the current code
- Keep changes minimal - only fix the specific issue
- Preserve formatting and indentation`, issue.Path, issue.LineStart, issue.Title, issue.Description, "```\n", code, "\n```")
}

func detectLanguage(filePath string) string {
	ext := strings.ToLower(filePath)
	switch {
	case strings.HasSuffix(ext, ".go"):
		return "go"
	case strings.HasSuffix(ext, ".py"):
		return "python"
	case strings.HasSuffix(ext, ".js"):
		return "javascript"
	case strings.HasSuffix(ext, ".ts"):
		return "typescript"
	case strings.HasSuffix(ext, ".java"):
		return "java"
	case strings.HasSuffix(ext, ".rs"):
		return "rust"
	case strings.HasSuffix(ext, ".rb"):
		return "ruby"
	case strings.HasSuffix(ext, ".php"):
		return "php"
	case strings.HasSuffix(ext, ".c"), strings.HasSuffix(ext, ".h"):
		return "c"
	case strings.HasSuffix(ext, ".cpp"), strings.HasSuffix(ext, ".hpp"):
		return "cpp"
	default:
		return ""
	}
}

func parseAnalysisResponse(response string) (*AIAnalysisResult, error) {
	// Try to extract JSON from response
	jsonStr := extractJSON(response)
	if jsonStr == "" {
		return nil, fmt.Errorf("no JSON found in response")
	}

	var result AIAnalysisResult
	if err := json.Unmarshal([]byte(jsonStr), &result); err != nil {
		return nil, fmt.Errorf("JSON parse error: %w", err)
	}

	// Validate insights
	for i := range result.Insights {
		insight := &result.Insights[i]
		// Normalize severity
		switch strings.ToLower(insight.Severity) {
		case "critical", "error":
			insight.Severity = "critical"
		case "warning", "warn":
			insight.Severity = "warning"
		default:
			insight.Severity = "info"
		}
		// Clamp confidence
		if insight.Confidence < 0 {
			insight.Confidence = 0
		} else if insight.Confidence > 1 {
			insight.Confidence = 1
		}
	}

	return &result, nil
}

func parseFixResponse(response string) (*AIFixResult, error) {
	jsonStr := extractJSON(response)
	if jsonStr == "" {
		return nil, fmt.Errorf("no JSON found in response")
	}

	var result AIFixResult
	if err := json.Unmarshal([]byte(jsonStr), &result); err != nil {
		return nil, fmt.Errorf("JSON parse error: %w", err)
	}

	return &result, nil
}

func extractJSON(response string) string {
	// Try to find JSON object in response
	// First, try to find {...}
	start := strings.Index(response, "{")
	if start == -1 {
		return ""
	}

	// Find matching closing brace
	depth := 0
	for i := start; i < len(response); i++ {
		switch response[i] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return response[start : i+1]
			}
		}
	}

	return ""
}

// ConvertInsightsToIssues converts AI insights to Issue structs.
func ConvertInsightsToIssues(insights []AIInsight, filePath string) []Issue {
	issues := make([]Issue, 0, len(insights))

	for i, insight := range insights {
		var severity Severity
		switch insight.Severity {
		case "critical":
			severity = SeverityError
		case "warning":
			severity = SeverityWarning
		default:
			severity = SeverityInfo
		}

		issues = append(issues, Issue{
			ID:          fmt.Sprintf("ai-%s:%s:%d", insight.Category, filePath, i),
			Title:       truncateString(insight.Description, 80),
			Description: insight.Description,
			Severity:    severity,
			Path:        filePath,
			LineStart:   insight.Line,
			Suggestions: []string{insight.Suggestion},
			Tags:        []string{"ai", insight.Category},
		})
	}

	return issues
}

func truncateString(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}

// ExtractCodeAroundLine extracts code context around a specific line.
func ExtractCodeAroundLine(code string, line, contextLines int) string {
	lines := strings.Split(code, "\n")
	if line <= 0 || line > len(lines) {
		return code
	}

	start := line - contextLines - 1
	if start < 0 {
		start = 0
	}
	end := line + contextLines
	if end > len(lines) {
		end = len(lines)
	}

	var result strings.Builder
	for i := start; i < end; i++ {
		lineNum := i + 1
		prefix := "  "
		if lineNum == line {
			prefix = "> "
		}
		result.WriteString(fmt.Sprintf("%s%4d: %s\n", prefix, lineNum, lines[i]))
	}

	return result.String()
}

// FilterHighConfidenceInsights filters insights by confidence threshold.
func FilterHighConfidenceInsights(insights []AIInsight, threshold float64) []AIInsight {
	filtered := make([]AIInsight, 0, len(insights))
	for _, insight := range insights {
		if insight.Confidence >= threshold {
			filtered = append(filtered, insight)
		}
	}
	return filtered
}

// ParseLineNumberFromSnippet tries to extract line number from diff snippet.
func ParseLineNumberFromSnippet(snippet string) int {
	// Try to find @@ -x,y +a,b @@ pattern
	re := regexp.MustCompile(`@@\s*-\d+(?:,\d+)?\s*\+(\d+)`)
	matches := re.FindStringSubmatch(snippet)
	if len(matches) >= 2 {
		if n, err := strconv.Atoi(matches[1]); err == nil {
			return n
		}
	}
	return 0
}
