// Code generated by gen-help.go. DO NOT EDIT.

package agent

// GeneratedHelpCommandsText は自動生成された Classic ヘルプのコマンド一覧。
const GeneratedHelpCommandsText = `Commands:
  /exit, /quit, /q          - Exit the CLI
  /new                      - Start a new session
  /clear                    - Clear transcript and start a new session
  /history                  - Show conversation history
  /resume [--last|--all|id] - Resume a saved session
  /status, /stats           - Show current state, last request, and session statistics
  /tokens                   - Show token usage and context window status
  /ledger                   - Show runtime task ledger
  /rawoutputs [summary|verify|refs|gc --dry-run] - Inspect raw output artifact store diagnostics
  /mcp [status]             - Show MCP runtime status
                            /mcp status - Show current MCP session servers and tool surface
  /copy [code] [-n N]       - Copy last AI output to clipboard (code=code blocks only, -n=N-th last output)
  /compress [N] [-c]        - Compress history (keep recent N, -c: use OpenAI Compact API)
  /provider [provider] [model] - Open provider/model picker or switch directly
  /providers                - Show provider credential status
  /setup                    - Show first-run setup checklist
  /config                   - Edit global config.yaml settings
                            /config show - Show all settings with diff from defaults
                            /config model <name> - Change default model
  /skills                   - Pick skills or inspect the Agent Skills catalog
                            /skills overview - Print skill catalog overview
                            /skills show <name> - Show SKILL.md body and resource listings
                            /skills suggest <text> - Preview ranked Skill Router recommendations
                            /skills usage - Show local Skill Router usage diagnostics
                            /skills doctor - Show parsing/duplicate diagnostics
  /model [name]             - Open model picker or switch current provider model
  /init                     - Create project AGENTS.md guidance file
  /plan [on|off|toggle|status] - Toggle Plan Mode (investigation -> plan -> approval -> implementation)
  /thinking <on|off|level>  - Set Extended Thinking mode (level: low/medium/high/xhigh=max)
  /version                  - Show version information
  /help, /h                 - Show this help
`

// GeneratedTUIHelpCommandsText は自動生成された TUI ヘルプのコマンド一覧。
const GeneratedTUIHelpCommandsText = `Commands:
  /exit, /quit, /q          - Exit the CLI
  /new                      - Start a new session
  /clear                    - Clear transcript and start a new session
  /history                  - Show conversation history
  /resume [--last|--all|id] - Resume a saved session
  /status, /stats           - Show current state, last request, and session statistics
  /tokens                   - Show token usage and context window status
  /ledger                   - Show runtime task ledger
  /rawoutputs [summary|verify|refs|gc --dry-run] - Inspect raw output artifact store diagnostics
  /mcp [status]             - Show MCP runtime status
                            /mcp status - Show current MCP session servers and tool surface
  /copy [code] [-n N]       - Copy last AI output to clipboard (code=code blocks only, -n=N-th last output)
  /attach <path>            - Attach a file or image to the current composer draft (combined limit: up to 12 attachments per draft)
  /detach <index>           - Detach one attachment by index
  /detach-all               - Detach all attachments from the current draft
  /review [instructions]    - Review current changes and find issues
  /compress [N] [-c]        - Compress history (keep recent N, -c: use OpenAI Compact API)
  /provider [provider] [model] - Open provider/model picker or switch directly
  /providers                - Show provider credential status
  /setup                    - Show first-run setup checklist
  /config                   - Edit global config.yaml settings
                            /config show - Show all settings with diff from defaults
                            /config model <name> - Change default model
  /skills                   - Pick skills or inspect the Agent Skills catalog
                            /skills overview - Print skill catalog overview
                            /skills show <name> - Show SKILL.md body and resource listings
                            /skills suggest <text> - Preview ranked Skill Router recommendations
                            /skills usage - Show local Skill Router usage diagnostics
                            /skills doctor - Show parsing/duplicate diagnostics
  /model [name]             - Open model picker or switch current provider model
  /init                     - Create project AGENTS.md guidance file
  /project                  - Edit project xelyon.yaml interactively
  /plan [on|off|toggle|status] - Toggle Plan Mode (investigation -> plan -> approval -> implementation)
  /thinking <on|off|level>  - Set Extended Thinking mode (level: low/medium/high/xhigh=max)
  /version                  - Show version information
  /help, /h                 - Show this help
`

// GeneratedHelpTipsText は自動生成されたヘルプの Tips 一覧。
const GeneratedHelpTipsText = `Tips:
  - Just describe what you want in natural language
  - AI will ask confirmation for dangerous operations
  - Use Ctrl+C to cancel current operation
  - Use git to revert file changes when needed
`
