package configregistry

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/susugadx/xelyon-cli/scripts/internal/configmeta"
)

// GenerateRegistrySource は config metadata から registry_generated.go の内容を生成する。
func GenerateRegistrySource() ([]byte, error) {
	var sb strings.Builder

	sb.WriteString(`// Code generated by gen-config-registry.go. DO NOT EDIT.

package config

// ConfigFieldType はフィールドの型
type ConfigFieldType int

const (
	FieldTypeBool ConfigFieldType = iota
	FieldTypeInt
	FieldTypeString
	FieldTypeSelect      // 選択肢付き文字列
	FieldTypeFloat                    // float64
	FieldTypeStringSlice // []string
	FieldTypeStringMap   // map[string]string
	FieldTypeStructMap   // map[string]struct
)

// CategoryDef はカテゴリ定義
type CategoryDef struct {
	Name        string   // カテゴリ名
	DisplayName string   // 表示名
	Icon        string   // アイコン
	Fields      []string // フィールドパス
}

`)

	writeCategoryDefinitions(&sb)

	fieldTypeEntries, err := buildRegistryFieldTypeEntries()
	if err != nil {
		return nil, fmt.Errorf("building FieldTypeMap entries: %w", err)
	}
	writeFieldTypeMap(&sb, fieldTypeEntries)
	writeSelectOptions(&sb, buildRegistrySelectEntries())
	writeFieldDescriptions(&sb, buildRegistryDescriptionEntries())

	formatted, err := format.Source([]byte(sb.String()))
	if err != nil {
		return nil, fmt.Errorf("formatting generated code: %w", err)
	}
	return formatted, nil
}

func writeCategoryDefinitions(sb *strings.Builder) {
	sb.WriteString("// CategoryDefinitions はカテゴリ定義リスト\n")
	sb.WriteString("var CategoryDefinitions = []CategoryDef{\n")
	for _, catName := range configmeta.CategoryOrder {
		cat := configmeta.Categories[catName]
		fields := collectCategoryFields(catName)
		fmt.Fprintf(sb, "\t{Name: %q, DisplayName: %q, Icon: %q, Fields: []string{",
			catName, cat.DisplayName, cat.Icon)
		for i, field := range fields {
			if i > 0 {
				sb.WriteString(", ")
			}
			fmt.Fprintf(sb, "%q", field)
		}
		sb.WriteString("}},\n")
	}
	sb.WriteString("}\n\n")
}

func writeFieldTypeMap(sb *strings.Builder, entries []registryFieldTypeEntry) {
	sb.WriteString("// FieldTypeMap はフィールドパスから型へのマップ\n")
	sb.WriteString("var FieldTypeMap = map[string]ConfigFieldType{\n")
	for _, entry := range entries {
		fmt.Fprintf(sb, "\t%q: %s,\n", entry.Path, entry.FieldType)
	}
	sb.WriteString("}\n\n")
}

func writeSelectOptions(sb *strings.Builder, entries []registrySelectEntry) {
	sb.WriteString("// SelectOptions は選択型フィールドの選択肢\n")
	sb.WriteString("var SelectOptions = map[string][]string{\n")
	for _, entry := range entries {
		fmt.Fprintf(sb, "\t%q: {", entry.Path)
		for i, opt := range entry.Options {
			if i > 0 {
				sb.WriteString(", ")
			}
			fmt.Fprintf(sb, "%q", opt)
		}
		sb.WriteString("},\n")
	}
	sb.WriteString("}\n\n")
}

func writeFieldDescriptions(sb *strings.Builder, entries []registryDescriptionEntry) {
	sb.WriteString("// FieldDescriptions はフィールドの説明\n")
	sb.WriteString("var FieldDescriptions = map[string]string{\n")
	for _, entry := range entries {
		fmt.Fprintf(sb, "\t%q: %q,\n", entry.Path, entry.Description)
	}
	sb.WriteString("}\n\n")
}
