package helpgen

import (
	"bytes"

	"github.com/susugadx/xelyon-cli/internal/commandcatalog"
)

// GenerateHelpSource は internal/agent/help_generated.go の内容を生成する。
func GenerateHelpSource() []byte {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by gen-help.go. DO NOT EDIT.\n\n")
	buf.WriteString("package agent\n\n")
	buf.WriteString("// GeneratedHelpCommandsText は自動生成された Classic ヘルプのコマンド一覧。\n")
	buf.WriteString("const GeneratedHelpCommandsText = `")
	buf.WriteString(commandcatalog.RenderCommandsTextForSurface(commandcatalog.CommandSurfaceClassic))
	buf.WriteString("`\n\n")
	buf.WriteString("// GeneratedTUIHelpCommandsText は自動生成された TUI ヘルプのコマンド一覧。\n")
	buf.WriteString("const GeneratedTUIHelpCommandsText = `")
	buf.WriteString(commandcatalog.RenderCommandsTextForSurface(commandcatalog.CommandSurfaceTUI))
	buf.WriteString("`\n\n")
	buf.WriteString("// GeneratedHelpTipsText は自動生成されたヘルプの Tips 一覧。\n")
	buf.WriteString("const GeneratedHelpTipsText = `")
	buf.WriteString(commandcatalog.RenderTipsText())
	buf.WriteString("`\n")

	return buf.Bytes()
}
