package helpgen

import (
	"strings"
	"testing"
)

func TestGenerateHelpSourceShape(t *testing.T) {
	source := string(GenerateHelpSource())
	for _, expected := range []string{
		"// Code generated by gen-help.go. DO NOT EDIT.",
		"package agent",
		"const GeneratedHelpCommandsText = `",
		"const GeneratedTUIHelpCommandsText = `",
		"const GeneratedHelpTipsText = `",
		"/status",
	} {
		if !strings.Contains(source, expected) {
			t.Fatalf("generated help source missing %q in:\n%s", expected, source)
		}
	}
}
