package report

var coverageExternalEvidenceGapStatePhrases = []string{
	"failed",
	"failure",
	"no-result",
	"no result",
	"no external doc",
	"no citation-capable",
	"no official confirmation",
	"missing official confirmation",
	"official confirmation is absent",
	"official confirmation absent",
	"official confirmation is missing",
	"official confirmation missing",
	"official confirmation is unavailable",
	"official confirmation unavailable",
	"unconfirmed",
	"unverified",
	"residual",
	"blocked",
	"inconclusive",
	"insufficient",
	"truncated",
	"truncation",
	"weak external evidence",
	"weak external support",
	"weak support",
	"partial external support",
	"partial support",
	"needs verification",
	"need verification",
	"requires verification",
	"cannot establish",
	"cannot confirm",
	"cannot be established",
	"cannot be confirmed",
	"could not establish",
	"could not confirm",
	"could not be established",
	"could not be confirmed",
	"could not verify",
	"unable to establish",
	"unable to confirm",
	"can't establish",
	"can't confirm",
	"cannot verify",
	"not verified",
	"not available",
	"not present",
	"not found",
}

var coverageExternalEvidenceContextPhrases = []string{
	"external evidence",
	"external search",
	"web search",
	"external doc",
	"external_doc",
	"external support",
	"external specification",
	"external spec",
	"official confirmation",
	"official source",
	"citation-capable",
	"citation capable",
}

var coverageExternalSupportStatePhrases = []string{
	"weak external evidence",
	"weak external support",
	"weak support",
	"partial external support",
	"partial support",
	"no official confirmation",
	"missing official confirmation",
	"official confirmation is absent",
	"official confirmation absent",
	"official confirmation is missing",
	"official confirmation missing",
	"official confirmation is unavailable",
	"official confirmation unavailable",
	"unconfirmed external spec",
	"unconfirmed external specification",
	"not a confirmed external spec",
	"not a confirmed external specification",
}

var coveragePostPass1ExternalEvidencePhrases = []string{
	"post-pass1 external",
	"post pass1 external",
	"post-pass 1 external",
	"post pass 1 external",
	"plan-derived external",
	"added external evidence",
	"added external doc",
	"added external search",
}

var coverageExplicitAddedExternalDocPhrases = []string{
	"added external doc",
	"added external_doc",
	"new external doc",
	"new external_doc",
}

var coverageConfirmedExternalSpecStrongClaimPhrases = []string{
	"officially confirmed",
	"confirmed official",
	"confirmed external spec",
	"confirmed external specification",
	"official documentation confirms",
	"official docs confirm",
	"official doc confirms",
	"confirmed by official docs",
	"confirmed by official documentation",
	"confirmed by external spec",
	"confirmed by external specification",
	"external spec confirms",
	"external specification confirms",
	"official source confirms",
	"official source confirmed",
}

var coverageOfficialConfirmationSubjectPhrases = []string{
	"official confirmation",
}

var coverageOfficialConfirmationAssertionPrefixPhrases = []string{
	"found ",
	"obtained ",
	"established ",
	"verified ",
}

var coverageOfficialConfirmationAssertionSuffixPhrases = []string{
	" exists",
	" is present",
	" is available",
	" is confirmed",
	" is established",
	" is verified",
	" was present",
	" was available",
	" was found",
	" was confirmed",
	" was established",
	" was verified",
	" has been found",
	" has been confirmed",
	" has been established",
	" has been verified",
	" has been obtained",
	" confirms",
	" supports",
}

var coverageConfirmationPrefixNonClaimPhrases = []string{
	"no ",
	"no-",
	"not ",
	"not-",
	"not a ",
	"not an ",
	"without ",
	"lacks ",
	"absent ",
	"missing ",
	"insufficient ",
	"unverified ",
	"unconfirmed ",
	"need ",
	"needs ",
	"needed ",
	"require ",
	"requires ",
	"required ",
	"requiring ",
	"pending ",
	"awaiting ",
	"waiting for ",
	"obtain ",
	"obtain the ",
	"still need ",
	"still needs ",
	"still requiring ",
	"verify ",
	"verify the ",
	"verify whether ",
	"must obtain ",
	"must verify ",
	"should obtain ",
	"should verify ",
	"cannot establish ",
	"cannot confirm ",
	"cannot verify ",
	"could not establish ",
	"could not confirm ",
	"could not verify ",
	"unable to establish ",
	"unable to confirm ",
	"unable to verify ",
	"can't establish ",
	"can't confirm ",
	"can't verify ",
	"un-",
	"non-",
}

var coverageConfirmationPrefixClauseBoundaryPhrases = []string{
	" but ",
	" however ",
	" though ",
	" although ",
	" yet ",
}

var coverageConfirmationSuffixNonClaimPhrases = []string{
	" is absent",
	" remains absent",
	" is missing",
	" remains missing",
	" is unavailable",
	" remains unavailable",
	" is not available",
	" is not present",
	" is not found",
	" is not confirmed",
	" is not established",
	" was not found",
	" was not confirmed",
	" was not established",
	" could not be found",
	" could not be confirmed",
	" could not be established",
	" cannot be found",
	" cannot be confirmed",
	" cannot be established",
	" is unverified",
	" remains unverified",
	" is insufficient",
	" remains insufficient",
	" remains unconfirmed",
	" remains unestablished",
	" is needed",
	" is still needed",
	" remains needed",
	" is required",
	" is still required",
	" remains required",
	" is pending",
	" remains pending",
	" is still pending",
	" must be obtained",
	" must be verified",
	" should be obtained",
	" should be verified",
	" not available",
	" not present",
	" not confirmed",
	" not established",
	" absent",
	" missing",
	" unavailable",
}
