//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"
)

func main() {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by gen-help.go. DO NOT EDIT.\n\n")
	buf.WriteString("package agent\n\n")
	buf.WriteString("// GeneratedHelpCommandsText は自動生成されたヘルプのコマンド一覧。\n")
	buf.WriteString("const GeneratedHelpCommandsText = `Commands:\n")

	for _, cmd := range Commands {
		// コマンド名 + エイリアス + 引数
		name := cmd.Name
		if len(cmd.Aliases) > 0 {
			name += ", " + strings.Join(cmd.Aliases, ", ")
		}
		if cmd.Args != "" {
			name += " " + cmd.Args
		}

		// フォーマット: "  /command         - Description"
		line := fmt.Sprintf("  %-25s - %s\n", name, cmd.Description)
		buf.WriteString(line)

		// サブコマンド
		for _, sub := range cmd.SubCommands {
			subLine := fmt.Sprintf("                            %s - %s\n", sub.Name, sub.Description)
			buf.WriteString(subLine)
		}
	}

	buf.WriteString("`\n\n")
	buf.WriteString("// GeneratedHelpTipsText は自動生成されたヘルプの Tips 一覧。\n")
	buf.WriteString("const GeneratedHelpTipsText = `Tips:\n")
	for _, tip := range Tips {
		buf.WriteString(fmt.Sprintf("  - %s\n", tip))
	}

	buf.WriteString("`\n")

	// ファイル出力
	outputPath := "internal/agent/help_generated.go"
	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", outputPath)
}
