//go:build ignore

// gen-config-registry.go は config_sections.go から registry_generated.go を生成するスクリプト
//
// 使用方法:
//
//	go run scripts/config_sections.go scripts/gen-config-registry.go
//	make gen-registry
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

func main() {
	var sb strings.Builder

	// ヘッダー
	sb.WriteString(`// Code generated by gen-config-registry.go. DO NOT EDIT.

package config

// ConfigFieldType はフィールドの型
type ConfigFieldType int

const (
	FieldTypeBool ConfigFieldType = iota
	FieldTypeInt
	FieldTypeString
	FieldTypeSelect      // 選択肢付き文字列
	FieldTypeFloat                    // float64
	FieldTypeStringSlice // []string
	FieldTypeStringMap   // map[string]string
	FieldTypeStructMap   // map[string]struct
)

// CategoryDef はカテゴリ定義
type CategoryDef struct {
	Name        string   // カテゴリ名
	DisplayName string   // 表示名
	Icon        string   // アイコン
	Fields      []string // フィールドパス
}

`)

	// CategoryDefinitions を生成
	sb.WriteString("// CategoryDefinitions はカテゴリ定義リスト\n")
	sb.WriteString("var CategoryDefinitions = []CategoryDef{\n")

	for _, catName := range CategoryOrder {
		cat := Categories[catName]

		// このカテゴリに含まれるフィールドを収集
		var fields []string
		for _, sectionName := range cat.Sections {
			section, ok := Sections[sectionName]
			if !ok {
				continue
			}

			// セクション自体がフィールドの場合（command_aliases, provider_models 等）
			if _, ok := section.FieldTypes[sectionName]; ok {
				fields = append(fields, sectionName)
			}

			// セクション内のフィールド
			for fieldName := range section.Fields {
				if fieldName == sectionName {
					// トップレベルフィールド
					fields = append(fields, fieldName)
				} else {
					// ネストされたフィールド
					fields = append(fields, sectionName+"."+fieldName)
				}
			}
		}

		// 重複を除去してソート
		fields = uniqueStrings(fields)
		sort.Strings(fields)

		sb.WriteString(fmt.Sprintf("\t{Name: %q, DisplayName: %q, Icon: %q, Fields: []string{",
			catName, cat.DisplayName, cat.Icon))
		for i, f := range fields {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("%q", f))
		}
		sb.WriteString("}},\n")
	}
	sb.WriteString("}\n\n")

	// FieldTypeMap を生成
	sb.WriteString("// FieldTypeMap はフィールドパスから型へのマップ\n")
	sb.WriteString("var FieldTypeMap = map[string]ConfigFieldType{\n")

	var fieldPaths []string
	fieldTypeEntries := make(map[string]string)

	for sectionName, section := range Sections {
		for fieldName, fieldType := range section.FieldTypes {
			var path string
			if fieldName == sectionName {
				path = fieldName
			} else {
				path = sectionName + "." + fieldName
			}
			fieldPaths = append(fieldPaths, path)
			fieldTypeEntries[path] = fieldTypeToConst(fieldType)
		}
	}

	sort.Strings(fieldPaths)
	for _, path := range fieldPaths {
		sb.WriteString(fmt.Sprintf("\t%q: %s,\n", path, fieldTypeEntries[path]))
	}
	sb.WriteString("}\n\n")

	// SelectOptions を生成
	sb.WriteString("// SelectOptions は選択型フィールドの選択肢\n")
	sb.WriteString("var SelectOptions = map[string][]string{\n")

	var selectPaths []string
	selectEntries := make(map[string][]string)

	for sectionName, section := range Sections {
		for fieldName, opts := range section.SelectOpts {
			var path string
			if fieldName == sectionName {
				path = fieldName
			} else {
				path = sectionName + "." + fieldName
			}
			selectPaths = append(selectPaths, path)
			selectEntries[path] = opts
		}
	}

	sort.Strings(selectPaths)
	for _, path := range selectPaths {
		opts := selectEntries[path]
		sb.WriteString(fmt.Sprintf("\t%q: {", path))
		for i, opt := range opts {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("%q", opt))
		}
		sb.WriteString("},\n")
	}
	sb.WriteString("}\n\n")

	// FieldDescriptions を生成
	sb.WriteString("// FieldDescriptions はフィールドの説明\n")
	sb.WriteString("var FieldDescriptions = map[string]string{\n")

	var descPaths []string
	descEntries := make(map[string]string)

	for sectionName, section := range Sections {
		for fieldName, desc := range section.Fields {
			var path string
			if fieldName == sectionName {
				path = fieldName
			} else {
				path = sectionName + "." + fieldName
			}
			descPaths = append(descPaths, path)
			descEntries[path] = desc
		}
	}

	sort.Strings(descPaths)
	for _, path := range descPaths {
		sb.WriteString(fmt.Sprintf("\t%q: %q,\n", path, descEntries[path]))
	}
	sb.WriteString("}\n\n")

	// NOTE: CategoryIcons は CategoryDefinitions[i].Icon で代替されるため生成しない

	// ファイルに出力
	outputPath := "internal/config/registry_generated.go"
	if len(os.Args) > 1 {
		outputPath = os.Args[1]
	}

	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", outputPath)
}

func fieldTypeToConst(t string) string {
	switch t {
	case "bool":
		return "FieldTypeBool"
	case "int":
		return "FieldTypeInt"
	case "string":
		return "FieldTypeString"
	case "select":
		return "FieldTypeSelect"
	case "float":
		return "FieldTypeFloat"
	case "[]string":
		return "FieldTypeStringSlice"
	case "map":
		return "FieldTypeStringMap"
	case "structmap":
		return "FieldTypeStructMap"
	default:
		return "FieldTypeString"
	}
}

func uniqueStrings(s []string) []string {
	seen := make(map[string]bool)
	var result []string
	for _, v := range s {
		if !seen[v] {
			seen[v] = true
			result = append(result, v)
		}
	}
	return result
}
