//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/susugadx/xelyon-cli/internal/commandcatalog"
)

func main() {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by gen-help.go. DO NOT EDIT.\n\n")
	buf.WriteString("package agent\n\n")
	buf.WriteString("// GeneratedHelpCommandsText は自動生成されたヘルプのコマンド一覧。\n")
	buf.WriteString("const GeneratedHelpCommandsText = `")
	buf.WriteString(commandcatalog.RenderCommandsText())
	buf.WriteString("`\n\n")
	buf.WriteString("// GeneratedHelpTipsText は自動生成されたヘルプの Tips 一覧。\n")
	buf.WriteString("const GeneratedHelpTipsText = `")
	buf.WriteString(commandcatalog.RenderTipsText())
	buf.WriteString("`\n")

	// ファイル出力
	outputPath := "internal/agent/help_generated.go"
	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", outputPath)
}
