//go:build ignore

// gen-config-registry.go generates registry_generated.go from config metadata.
//
// Usage:
//
//	go run scripts/config_sections.go scripts/gen-config-registry.go
//	make gen-registry
package main

import (
	"fmt"
	"go/format"
	"os"
	"strings"

	configgen "github.com/susugadx/xelyon-cli/scripts/internal/configgen"
)

func main() {
	var sb strings.Builder

	sb.WriteString(`// Code generated by gen-config-registry.go. DO NOT EDIT.

package config

// ConfigFieldType はフィールドの型
type ConfigFieldType int

const (
	FieldTypeBool ConfigFieldType = iota
	FieldTypeInt
	FieldTypeString
	FieldTypeSelect      // 選択肢付き文字列
	FieldTypeFloat                    // float64
	FieldTypeStringSlice // []string
	FieldTypeStringMap   // map[string]string
	FieldTypeStructMap   // map[string]struct
)

// CategoryDef はカテゴリ定義
type CategoryDef struct {
	Name        string   // カテゴリ名
	DisplayName string   // 表示名
	Icon        string   // アイコン
	Fields      []string // フィールドパス
}

`)

	sb.WriteString("// CategoryDefinitions はカテゴリ定義リスト\n")
	sb.WriteString("var CategoryDefinitions = []CategoryDef{\n")
	for _, catName := range configgen.CategoryOrder {
		cat := configgen.Categories[catName]
		fields := configgen.CollectCategoryFields(catName)
		sb.WriteString(fmt.Sprintf("\t{Name: %q, DisplayName: %q, Icon: %q, Fields: []string{",
			catName, cat.DisplayName, cat.Icon))
		for i, field := range fields {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("%q", field))
		}
		sb.WriteString("}},\n")
	}
	sb.WriteString("}\n\n")

	fieldTypeEntries, err := configgen.BuildRegistryFieldTypeEntries()
	if err != nil {
		configgen.ExitWithError("Error building FieldTypeMap entries: %v", err)
	}
	sb.WriteString("// FieldTypeMap はフィールドパスから型へのマップ\n")
	sb.WriteString("var FieldTypeMap = map[string]ConfigFieldType{\n")
	for _, entry := range fieldTypeEntries {
		sb.WriteString(fmt.Sprintf("\t%q: %s,\n", entry.Path, entry.FieldType))
	}
	sb.WriteString("}\n\n")

	sb.WriteString("// SelectOptions は選択型フィールドの選択肢\n")
	sb.WriteString("var SelectOptions = map[string][]string{\n")
	for _, entry := range configgen.BuildRegistrySelectEntries() {
		sb.WriteString(fmt.Sprintf("\t%q: {", entry.Path))
		for i, opt := range entry.Options {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("%q", opt))
		}
		sb.WriteString("},\n")
	}
	sb.WriteString("}\n\n")

	sb.WriteString("// FieldDescriptions はフィールドの説明\n")
	sb.WriteString("var FieldDescriptions = map[string]string{\n")
	for _, entry := range configgen.BuildRegistryDescriptionEntries() {
		sb.WriteString(fmt.Sprintf("\t%q: %q,\n", entry.Path, entry.Description))
	}
	sb.WriteString("}\n\n")

	formatted, err := format.Source([]byte(sb.String()))
	if err != nil {
		configgen.ExitWithError("Error formatting generated code: %v", err)
	}

	outputPath := configgen.OutputPathFromArgs(os.Args, "internal/config/registry_generated.go")

	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		configgen.ExitWithError("Error writing file: %v", err)
	}

	fmt.Printf("Generated %s\n", outputPath)
}
