//go:build ignore

// gen-config-registry.go generates registry_generated.go from config metadata.
//
// Usage:
//
//	go run scripts/config_sections.go scripts/gen-config-registry.go
//	make gen-registry
package main

import (
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	configgen "github.com/susugadx/xelyon-cli/scripts/internal/configgen"
)

func main() {
	var sb strings.Builder

	sb.WriteString(`// Code generated by gen-config-registry.go. DO NOT EDIT.

package config

// ConfigFieldType はフィールドの型
type ConfigFieldType int

const (
	FieldTypeBool ConfigFieldType = iota
	FieldTypeInt
	FieldTypeString
	FieldTypeSelect      // 選択肢付き文字列
	FieldTypeFloat                    // float64
	FieldTypeStringSlice // []string
	FieldTypeStringMap   // map[string]string
	FieldTypeStructMap   // map[string]struct
)

// CategoryDef はカテゴリ定義
type CategoryDef struct {
	Name        string   // カテゴリ名
	DisplayName string   // 表示名
	Icon        string   // アイコン
	Fields      []string // フィールドパス
}

`)

	sb.WriteString("// CategoryDefinitions はカテゴリ定義リスト\n")
	sb.WriteString("var CategoryDefinitions = []CategoryDef{\n")
	for _, catName := range configgen.CategoryOrder {
		cat := configgen.Categories[catName]
		fields := configgen.CollectCategoryFields(catName)
		sb.WriteString(fmt.Sprintf("\t{Name: %q, DisplayName: %q, Icon: %q, Fields: []string{",
			catName, cat.DisplayName, cat.Icon))
		for i, field := range fields {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("%q", field))
		}
		sb.WriteString("}},\n")
	}
	sb.WriteString("}\n\n")

	sb.WriteString("// FieldTypeMap はフィールドパスから型へのマップ\n")
	sb.WriteString("var FieldTypeMap = map[string]ConfigFieldType{\n")
	var fieldPaths []string
	fieldTypeEntries := make(map[string]string)
	for sectionName, section := range configgen.Sections {
		for fieldName, fieldType := range section.FieldTypes {
			path := sectionName + "." + fieldName
			if fieldName == sectionName {
				path = fieldName
			}
			fieldPaths = append(fieldPaths, path)
			fieldTypeEntries[path] = configgen.FieldTypeToConst(fieldType)
		}
	}
	sort.Strings(fieldPaths)
	for _, path := range fieldPaths {
		sb.WriteString(fmt.Sprintf("\t%q: %s,\n", path, fieldTypeEntries[path]))
	}
	sb.WriteString("}\n\n")

	sb.WriteString("// SelectOptions は選択型フィールドの選択肢\n")
	sb.WriteString("var SelectOptions = map[string][]string{\n")
	var selectPaths []string
	selectEntries := make(map[string][]string)
	for sectionName, section := range configgen.Sections {
		for fieldName, opts := range section.SelectOpts {
			path := sectionName + "." + fieldName
			if fieldName == sectionName {
				path = fieldName
			}
			selectPaths = append(selectPaths, path)
			selectEntries[path] = opts
		}
	}
	sort.Strings(selectPaths)
	for _, path := range selectPaths {
		opts := selectEntries[path]
		sb.WriteString(fmt.Sprintf("\t%q: {", path))
		for i, opt := range opts {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("%q", opt))
		}
		sb.WriteString("},\n")
	}
	sb.WriteString("}\n\n")

	sb.WriteString("// FieldDescriptions はフィールドの説明\n")
	sb.WriteString("var FieldDescriptions = map[string]string{\n")
	var descPaths []string
	descEntries := make(map[string]string)
	for sectionName, section := range configgen.Sections {
		for fieldName, desc := range section.Fields {
			path := sectionName + "." + fieldName
			if fieldName == sectionName {
				path = fieldName
			}
			descPaths = append(descPaths, path)
			descEntries[path] = desc
		}
	}
	sort.Strings(descPaths)
	for _, path := range descPaths {
		sb.WriteString(fmt.Sprintf("\t%q: %q,\n", path, descEntries[path]))
	}
	sb.WriteString("}\n\n")

	formatted, err := format.Source([]byte(sb.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error formatting generated code: %v\n", err)
		os.Exit(1)
	}

	outputPath := "internal/config/registry_generated.go"
	if len(os.Args) > 1 {
		outputPath = os.Args[1]
	}

	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", outputPath)
}
