//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"github.com/susugadx/xelyon-cli/internal/commandcatalog"
)

func main() {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by gen-help.go. DO NOT EDIT.\n\n")
	buf.WriteString("package agent\n\n")
	buf.WriteString("// GeneratedHelpCommandsText は自動生成された Classic ヘルプのコマンド一覧。\n")
	buf.WriteString("const GeneratedHelpCommandsText = `")
	buf.WriteString(commandcatalog.RenderCommandsTextForSurface(commandcatalog.CommandSurfaceClassic))
	buf.WriteString("`\n\n")
	buf.WriteString("// GeneratedTUIHelpCommandsText は自動生成された TUI ヘルプのコマンド一覧。\n")
	buf.WriteString("const GeneratedTUIHelpCommandsText = `")
	buf.WriteString(commandcatalog.RenderCommandsTextForSurface(commandcatalog.CommandSurfaceTUI))
	buf.WriteString("`\n\n")
	buf.WriteString("// GeneratedHelpTipsText は自動生成されたヘルプの Tips 一覧。\n")
	buf.WriteString("const GeneratedHelpTipsText = `")
	buf.WriteString(commandcatalog.RenderTipsText())
	buf.WriteString("`\n")

	rootDir, err := resolveProjectRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error resolving project root: %v\n", err)
		os.Exit(1)
	}

	// ファイル出力
	outputPath := filepath.Join(rootDir, "internal", "agent", "help_generated.go")
	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", outputPath)
}

func resolveProjectRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for dir := wd; ; dir = filepath.Dir(dir) {
		if _, statErr := os.Stat(filepath.Join(dir, "go.mod")); statErr == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from %s", wd)
		}
	}
}
