// Code generated by gen-config-registry.go. DO NOT EDIT.

package config

// ConfigFieldType はフィールドの型
type ConfigFieldType int

const (
	FieldTypeBool ConfigFieldType = iota
	FieldTypeInt
	FieldTypeString
	FieldTypeSelect      // 選択肢付き文字列
	FieldTypeStringSlice // []string
	FieldTypeStringMap   // map[string]string
	FieldTypeStructMap   // map[string]struct
)

// CategoryDef はカテゴリ定義
type CategoryDef struct {
	Name        string   // カテゴリ名
	DisplayName string   // 表示名
	Icon        string   // アイコン
	Fields      []string // フィールドパス
}

// CategoryDefinitions はカテゴリ定義リスト
var CategoryDefinitions = []CategoryDef{
	{Name: "provider", DisplayName: "Provider & Model", Icon: "🤖", Fields: []string{"default_model", "default_provider", "provider_models"}},
	{Name: "compression", DisplayName: "Compression", Icon: "📦", Fields: []string{"compression.auto_compress", "compression.keep_recent", "compression.prefer_compact_api", "compression.threshold_percent", "compression.threshold_tokens"}},
	{Name: "backup", DisplayName: "Backup", Icon: "💾", Fields: []string{"backup.max_generations"}},
	{Name: "loop_detection", DisplayName: "Loop Detection", Icon: "🔄", Fields: []string{"loop_detection.threshold"}},
	{Name: "api_retry", DisplayName: "API Settings", Icon: "🌐", Fields: []string{"api_retry.count", "api_retry.initial_delay", "api_retry.max_delay", "api_retry.timeout"}},
	{Name: "diff", DisplayName: "Diff Display", Icon: "📝", Fields: []string{"diff.context_lines"}},
	{Name: "tool_confirm", DisplayName: "Tool Confirm", Icon: "✅", Fields: []string{"tool_confirm.auto_approve_medium", "tool_confirm.auto_approve_safe"}},
	{Name: "command_aliases", DisplayName: "Command Aliases", Icon: "🔗", Fields: []string{"command_aliases"}},
	{Name: "prompt_cache", DisplayName: "Prompt Cache", Icon: "💨", Fields: []string{"prompt_cache.enabled", "prompt_cache.max_entries", "prompt_cache.ttl_seconds"}},
	{Name: "paste", DisplayName: "Paste Mode", Icon: "📋", Fields: []string{"paste.bracketed_paste", "paste.max_bytes", "paste.max_lines", "paste.timeout_seconds"}},
	{Name: "streaming", DisplayName: "Streaming", Icon: "📺", Fields: []string{"streaming.idle_timeout_seconds", "streaming.show_file_info", "streaming.show_search_progress", "streaming.stream_bash_output"}},
	{Name: "bash", DisplayName: "Bash Safety", Icon: "💻", Fields: []string{"bash.allow_inline_edit", "bash.allow_pipe", "bash.allow_redirect", "bash.safe_commands", "bash.safety_level"}},
	{Name: "code_health", DisplayName: "Code Health", Icon: "🏥", Fields: []string{"code_health.auto_suggest", "code_health.enabled", "code_health.max_file_lines", "code_health.max_function_lines", "code_health.on_change"}},
	{Name: "git_stage", DisplayName: "Git Settings", Icon: "📂", Fields: []string{"git_stage.batch_confirm"}},
	{Name: "plan_mode", DisplayName: "Plan Mode", Icon: "📋", Fields: []string{"plan_mode.confirm_level", "plan_mode.max_retry", "plan_mode.max_workers", "plan_mode.parallel", "plan_mode.step_timeout", "plan_mode.supervisor_model", "plan_mode.worker_model"}},
	{Name: "lsp", DisplayName: "LSP Servers", Icon: "🔧", Fields: []string{"lsp.enabled", "lsp.skip_install_prompt"}},
	{Name: "openai", DisplayName: "OpenAI", Icon: "🌟", Fields: []string{"openai.responses_api_models"}},
	{Name: "thinking", DisplayName: "Thinking", Icon: "🧠", Fields: []string{"thinking.enabled", "thinking.level"}},
	{Name: "output", DisplayName: "Output", Icon: "📤", Fields: []string{"output.max_lines"}},
	{Name: "web_search", DisplayName: "Web Search", Icon: "🔍", Fields: []string{"web_search.cache_enabled", "web_search.cache_size", "web_search.cache_ttl"}},
	{Name: "mcp", DisplayName: "MCP Servers", Icon: "🔌", Fields: []string{"mcp.enabled", "mcp.headless"}},
}

// FieldTypeMap はフィールドパスから型へのマップ
var FieldTypeMap = map[string]ConfigFieldType{
	"api_retry.count":                  FieldTypeInt,
	"api_retry.initial_delay":          FieldTypeInt,
	"api_retry.max_delay":              FieldTypeInt,
	"api_retry.timeout":                FieldTypeInt,
	"backup.max_generations":           FieldTypeInt,
	"bash.allow_inline_edit":           FieldTypeBool,
	"bash.allow_pipe":                  FieldTypeBool,
	"bash.allow_redirect":              FieldTypeBool,
	"bash.safe_commands":               FieldTypeStringSlice,
	"bash.safety_level":                FieldTypeSelect,
	"code_health.auto_suggest":         FieldTypeBool,
	"code_health.enabled":              FieldTypeBool,
	"code_health.max_file_lines":       FieldTypeInt,
	"code_health.max_function_lines":   FieldTypeInt,
	"code_health.on_change":            FieldTypeStringSlice,
	"command_aliases":                  FieldTypeStringMap,
	"compression.auto_compress":        FieldTypeBool,
	"compression.keep_recent":          FieldTypeInt,
	"compression.prefer_compact_api":   FieldTypeBool,
	"compression.threshold_percent":    FieldTypeInt,
	"compression.threshold_tokens":     FieldTypeInt,
	"default_model":                    FieldTypeString,
	"default_provider":                 FieldTypeSelect,
	"diff.context_lines":               FieldTypeInt,
	"general.language":                 FieldTypeSelect,
	"general.tool_loop_limit":          FieldTypeInt,
	"git_stage.batch_confirm":          FieldTypeBool,
	"loop_detection.threshold":         FieldTypeInt,
	"lsp.enabled":                      FieldTypeBool,
	"lsp.servers":                      FieldTypeStructMap,
	"lsp.skip_install_prompt":          FieldTypeBool,
	"mcp.enabled":                      FieldTypeBool,
	"mcp.headless":                     FieldTypeBool,
	"openai.responses_api_models":      FieldTypeStringSlice,
	"output.max_lines":                 FieldTypeInt,
	"paste.bracketed_paste":            FieldTypeBool,
	"paste.max_bytes":                  FieldTypeInt,
	"paste.max_lines":                  FieldTypeInt,
	"paste.timeout_seconds":            FieldTypeInt,
	"plan_mode.confirm_level":          FieldTypeSelect,
	"plan_mode.max_retry":              FieldTypeInt,
	"plan_mode.max_workers":            FieldTypeInt,
	"plan_mode.parallel":               FieldTypeBool,
	"plan_mode.step_timeout":           FieldTypeInt,
	"plan_mode.supervisor_model":       FieldTypeString,
	"plan_mode.worker_model":           FieldTypeString,
	"prompt_cache.enabled":             FieldTypeBool,
	"prompt_cache.max_entries":         FieldTypeInt,
	"prompt_cache.ttl_seconds":         FieldTypeInt,
	"provider_models":                  FieldTypeStructMap,
	"streaming.idle_timeout_seconds":   FieldTypeInt,
	"streaming.show_file_info":         FieldTypeBool,
	"streaming.show_search_progress":   FieldTypeBool,
	"streaming.stream_bash_output":     FieldTypeBool,
	"thinking.enabled":                 FieldTypeBool,
	"thinking.level":                   FieldTypeSelect,
	"tool_confirm.auto_approve_medium": FieldTypeBool,
	"tool_confirm.auto_approve_safe":   FieldTypeBool,
	"web_search.cache_enabled":         FieldTypeBool,
	"web_search.cache_size":            FieldTypeInt,
	"web_search.cache_ttl":             FieldTypeInt,
}

// SelectOptions は選択型フィールドの選択肢
var SelectOptions = map[string][]string{
	"bash.safety_level":       {"strict", "moderate", "permissive"},
	"default_provider":        {"deepseek", "claude", "openai", "gemini", "groq", "ollama", "openrouter", "bedrock"},
	"general.language":        {"ja", "en"},
	"plan_mode.confirm_level": {"all", "dangerous", "none"},
	"thinking.level":          {"low", "medium", "high", "xhigh"},
}

// FieldDescriptions はフィールドの説明
var FieldDescriptions = map[string]string{
	"api_retry.count":                  "リトライ回数",
	"api_retry.initial_delay":          "初回リトライ待機時間（秒）",
	"api_retry.max_delay":              "最大待機時間（秒）",
	"api_retry.timeout":                "タイムアウト（秒）",
	"backup.max_generations":           "保持する世代数",
	"bash.allow_inline_edit":           "インライン編集を許可（sed -i 等）",
	"bash.allow_pipe":                  "パイプを許可",
	"bash.allow_redirect":              "リダイレクトを許可",
	"bash.safe_commands":               "追加の安全コマンド（例: - \"npm run\"）",
	"bash.safety_level":                "安全レベル: strict / moderate / permissive",
	"code_health.auto_suggest":         "変更時に自動提案",
	"code_health.enabled":              "有効化",
	"code_health.max_file_lines":       "ファイルの最大行数警告",
	"code_health.max_function_lines":   "関数の最大行数警告",
	"code_health.on_change":            "変更時のチェック項目",
	"compression.auto_compress":        "トークン使用率が閾値を超えたら自動圧縮",
	"compression.keep_recent":          "圧縮時に保持する直近メッセージ数",
	"compression.prefer_compact_api":   "プロバイダーのCompact APIを優先使用",
	"compression.threshold_percent":    "トークン使用率の閾値（%）",
	"compression.threshold_tokens":     "トークン数の閾値（0 = 使用しない）",
	"default_model":                    "デフォルトで使用するモデル",
	"default_provider":                 "デフォルトで使用するLLMプロバイダー",
	"diff.context_lines":               "差分表示時のコンテキスト行数",
	"general.language":                 "表示言語（ja, en）",
	"general.tool_loop_limit":          "ツールループ最大回数",
	"git_stage.batch_confirm":          "複数ファイルをまとめて確認",
	"loop_detection.threshold":         "同じツール呼び出しの繰り返し回数でループと判定",
	"lsp.enabled":                      "LSP連携の有効/無効",
	"lsp.skip_install_prompt":          "インストール提案をスキップ",
	"mcp.enabled":                      "MCP接続を有効化（デフォルト: true）",
	"mcp.headless":                     "Headlessモードでも接続（デフォルト: false）",
	"openai.responses_api_models":      "Responses APIを使用するモデル",
	"output.max_lines":                 "折りたたみ前の最大表示行数",
	"paste.bracketed_paste":            "Bracketed Paste Mode を有効化（複数行ペースト対応）",
	"paste.max_bytes":                  "最大バイト数",
	"paste.max_lines":                  "最大行数",
	"paste.timeout_seconds":            "タイムアウト（秒）",
	"plan_mode.confirm_level":          "確認レベル: all / dangerous / none",
	"plan_mode.max_retry":              "最大リトライ回数",
	"plan_mode.max_workers":            "並列ワーカー数",
	"plan_mode.parallel":               "並列モード有効化",
	"plan_mode.step_timeout":           "ステップタイムアウト（秒）",
	"plan_mode.supervisor_model":       "Supervisor用モデル（空=メインモデル）",
	"plan_mode.worker_model":           "Worker用モデル（空=メインモデル）",
	"prompt_cache.enabled":             "有効化",
	"prompt_cache.max_entries":         "最大エントリ数",
	"prompt_cache.ttl_seconds":         "キャッシュTTL（秒）",
	"provider_models":                  "プロバイダーごとのモデル設定",
	"streaming.idle_timeout_seconds":   "アイドルタイムアウト（秒）",
	"streaming.show_file_info":         "ファイル読み込み時にサイズ・行数を表示",
	"streaming.show_search_progress":   "検索時に進捗を表示",
	"streaming.stream_bash_output":     "bashコマンドの出力をリアルタイム表示",
	"thinking.enabled":                 "有効化",
	"thinking.level":                   "レベル: low / medium / high / xhigh",
	"tool_confirm.auto_approve_medium": "中程度のツール（write_file等）を自動承認",
	"tool_confirm.auto_approve_safe":   "安全なツール（read_file等）を自動承認",
	"web_search.cache_enabled":         "キャッシュを有効化（デフォルト: true）",
	"web_search.cache_size":            "最大キャッシュ数（デフォルト: 100）",
	"web_search.cache_ttl":             "キャッシュTTL秒数（デフォルト: 1800 = 30分）",
}

// CategoryIcons はカテゴリのアイコン
var CategoryIcons = map[string]string{
	"api_retry":       "🌐",
	"backup":          "💾",
	"bash":            "💻",
	"code_health":     "🏥",
	"command_aliases": "🔗",
	"compression":     "📦",
	"diff":            "📝",
	"git_stage":       "📂",
	"loop_detection":  "🔄",
	"lsp":             "🔧",
	"mcp":             "🔌",
	"openai":          "🌟",
	"output":          "📤",
	"paste":           "📋",
	"plan_mode":       "📋",
	"prompt_cache":    "💨",
	"provider":        "🤖",
	"streaming":       "📺",
	"thinking":        "🧠",
	"tool_confirm":    "✅",
	"web_search":      "🔍",
}
