// Code generated by gen-config-registry.go. DO NOT EDIT.

package config

// ConfigFieldType はフィールドの型
type ConfigFieldType int

const (
	FieldTypeBool ConfigFieldType = iota
	FieldTypeInt
	FieldTypeString
	FieldTypeSelect      // 選択肢付き文字列
	FieldTypeFloat       // float64
	FieldTypeStringSlice // []string
	FieldTypeStringMap   // map[string]string
	FieldTypeStructMap   // map[string]struct
)

// CategoryDef はカテゴリ定義
type CategoryDef struct {
	Name        string   // カテゴリ名
	DisplayName string   // 表示名
	Icon        string   // アイコン
	Fields      []string // フィールドパス
}

// CategoryDefinitions はカテゴリ定義リスト
var CategoryDefinitions = []CategoryDef{
	{Name: "provider", DisplayName: "Provider & Model", Icon: "🤖", Fields: []string{"default_model", "default_provider", "provider_models"}},
	{Name: "general", DisplayName: "General", Icon: "⚙️", Fields: []string{"general.ui_language"}},
	{Name: "compression", DisplayName: "Compression", Icon: "📦", Fields: []string{"compression.enabled", "compression.keep_recent", "compression.trigger_percent"}},
	{Name: "tool_confirm", DisplayName: "Tool Confirm", Icon: "✅", Fields: []string{"tool_confirm.auto_approve_medium", "tool_confirm.auto_approve_safe"}},
	{Name: "command_aliases", DisplayName: "Command Aliases", Icon: "🔗", Fields: []string{"command_aliases"}},
	{Name: "prompt_cache", DisplayName: "Prompt Cache", Icon: "💨", Fields: []string{"prompt_cache.cache_ttl", "prompt_cache.enabled"}},
	{Name: "paste", DisplayName: "Paste Mode", Icon: "📋", Fields: []string{"paste.bracketed_paste", "paste.max_bytes", "paste.max_lines", "paste.timeout_seconds"}},
	{Name: "streaming", DisplayName: "Streaming", Icon: "📺", Fields: []string{"streaming.idle_timeout_seconds", "streaming.show_file_info", "streaming.show_search_progress", "streaming.stream_bash_output", "streaming.thinking_timeout_seconds"}},
	{Name: "bash", DisplayName: "Bash Safety", Icon: "💻", Fields: []string{"bash.allow_inline_edit", "bash.allow_pipe", "bash.allow_redirect", "bash.safe_commands", "bash.safety_level"}},
	{Name: "project_map", DisplayName: "Project Map", Icon: "🗺️", Fields: []string{"project_map.additional_ignore_dirs", "project_map.context_ratio", "project_map.enabled"}},
	{Name: "git_stage", DisplayName: "Git Settings", Icon: "📂", Fields: []string{"git_stage.batch_confirm"}},
	{Name: "plan_mode", DisplayName: "Plan Mode", Icon: "📋", Fields: []string{"plan_mode.clear_context_on_approval", "plan_mode.max_retry", "plan_mode.step_timeout"}},
	{Name: "lsp", DisplayName: "LSP Servers", Icon: "🔧", Fields: []string{"lsp.enabled", "lsp.skip_install_prompt"}},
	{Name: "openai", DisplayName: "OpenAI", Icon: "🌟", Fields: []string{"openai.responses_api_models"}},
	{Name: "thinking", DisplayName: "Thinking", Icon: "🧠", Fields: []string{"thinking.enabled", "thinking.level"}},
	{Name: "output", DisplayName: "Output", Icon: "📤", Fields: []string{"output.assistant_updates", "output.max_lines"}},
	{Name: "web_search", DisplayName: "Web Search", Icon: "🔍", Fields: []string{"web_search.cache_enabled", "web_search.cache_size", "web_search.cache_ttl", "web_search.provider"}},
	{Name: "sub_agent", DisplayName: "Sub-agent", Icon: "🚀", Fields: []string{"sub_agent.default_effort", "sub_agent.default_model", "sub_agent.enabled", "sub_agent.max_concurrent"}},
	{Name: "utility_model", DisplayName: "Utility Model", Icon: "🪶", Fields: []string{"utility_model.enabled", "utility_model.model", "utility_model.provider", "utility_model.tasks"}},
	{Name: "mcp", DisplayName: "MCP Servers", Icon: "🔌", Fields: []string{"mcp.enabled", "mcp.headless"}},
	{Name: "hooks", DisplayName: "Hooks", Icon: "🏁", Fields: []string{"hooks.max_retry", "hooks.on_completion", "hooks.on_step_complete", "hooks.timeout"}},
}

// FieldTypeMap はフィールドパスから型へのマップ
var FieldTypeMap = map[string]ConfigFieldType{
	"bash.allow_inline_edit":              FieldTypeBool,
	"bash.allow_pipe":                     FieldTypeBool,
	"bash.allow_redirect":                 FieldTypeBool,
	"bash.safe_commands":                  FieldTypeStringSlice,
	"bash.safety_level":                   FieldTypeSelect,
	"command_aliases":                     FieldTypeStringMap,
	"compression.enabled":                 FieldTypeBool,
	"compression.keep_recent":             FieldTypeInt,
	"compression.trigger_percent":         FieldTypeInt,
	"default_model":                       FieldTypeString,
	"default_provider":                    FieldTypeSelect,
	"general.ui_language":                 FieldTypeSelect,
	"git_stage.batch_confirm":             FieldTypeBool,
	"hooks.max_retry":                     FieldTypeInt,
	"hooks.on_completion":                 FieldTypeStringSlice,
	"hooks.on_step_complete":              FieldTypeStringSlice,
	"hooks.timeout":                       FieldTypeInt,
	"lsp.enabled":                         FieldTypeBool,
	"lsp.servers":                         FieldTypeStructMap,
	"lsp.skip_install_prompt":             FieldTypeBool,
	"mcp.enabled":                         FieldTypeBool,
	"mcp.headless":                        FieldTypeBool,
	"openai.responses_api_models":         FieldTypeStringSlice,
	"output.assistant_updates":            FieldTypeSelect,
	"output.max_lines":                    FieldTypeInt,
	"paste.bracketed_paste":               FieldTypeBool,
	"paste.max_bytes":                     FieldTypeInt,
	"paste.max_lines":                     FieldTypeInt,
	"paste.timeout_seconds":               FieldTypeInt,
	"plan_mode.clear_context_on_approval": FieldTypeBool,
	"plan_mode.max_retry":                 FieldTypeInt,
	"plan_mode.step_timeout":              FieldTypeInt,
	"project_map.additional_ignore_dirs":  FieldTypeStringSlice,
	"project_map.context_ratio":           FieldTypeFloat,
	"project_map.enabled":                 FieldTypeBool,
	"prompt_cache.cache_ttl":              FieldTypeString,
	"prompt_cache.enabled":                FieldTypeBool,
	"provider_models":                     FieldTypeStructMap,
	"streaming.idle_timeout_seconds":      FieldTypeInt,
	"streaming.show_file_info":            FieldTypeBool,
	"streaming.show_search_progress":      FieldTypeBool,
	"streaming.stream_bash_output":        FieldTypeBool,
	"streaming.thinking_timeout_seconds":  FieldTypeInt,
	"sub_agent.default_effort":            FieldTypeSelect,
	"sub_agent.default_model":             FieldTypeString,
	"sub_agent.enabled":                   FieldTypeBool,
	"sub_agent.max_concurrent":            FieldTypeInt,
	"thinking.enabled":                    FieldTypeBool,
	"thinking.level":                      FieldTypeSelect,
	"tool_confirm.auto_approve_medium":    FieldTypeBool,
	"tool_confirm.auto_approve_safe":      FieldTypeBool,
	"utility_model.enabled":               FieldTypeBool,
	"utility_model.model":                 FieldTypeString,
	"utility_model.provider":              FieldTypeSelect,
	"utility_model.tasks":                 FieldTypeStringSlice,
	"web_search.cache_enabled":            FieldTypeBool,
	"web_search.cache_size":               FieldTypeInt,
	"web_search.cache_ttl":                FieldTypeInt,
	"web_search.provider":                 FieldTypeSelect,
}

// SelectOptions は選択型フィールドの選択肢
var SelectOptions = map[string][]string{
	"bash.safety_level":        {"strict", "moderate", "permissive"},
	"default_provider":         {"deepseek", "claude", "openai", "gemini", "groq", "ollama", "openrouter", "bedrock"},
	"general.ui_language":      {"auto", "ja", "en"},
	"output.assistant_updates": {"", "verbose", "phase", "off"},
	"sub_agent.default_effort": {"off", "low", "medium", "high"},
	"thinking.level":           {"low", "medium", "high", "xhigh"},
	"utility_model.provider":   {"openai", "gemini", "claude", "deepseek", "openrouter", "groq", "ollama", "bedrock"},
	"web_search.provider":      {"openai", "gemini", "claude"},
}

// FieldDescriptions はフィールドの説明
var FieldDescriptions = map[string]string{
	"bash.allow_inline_edit":              "インライン編集を許可（sed -i 等）",
	"bash.allow_pipe":                     "パイプを許可",
	"bash.allow_redirect":                 "リダイレクトを許可",
	"bash.safe_commands":                  "追加の安全コマンド（例: - \"npm run\"）",
	"bash.safety_level":                   "安全レベル: strict / moderate / permissive",
	"compression.enabled":                 "自動圧縮を有効化",
	"compression.keep_recent":             "圧縮時に保持する直近メッセージ数",
	"compression.trigger_percent":         "自動圧縮のトークン使用率閾値（%）",
	"default_model":                       "デフォルトで使用するモデル",
	"default_provider":                    "デフォルトで使用するLLMプロバイダー",
	"general.ui_language":                 "表示言語（auto, ja, en）",
	"git_stage.batch_confirm":             "複数ファイルをまとめて確認",
	"hooks.max_retry":                     "フック失敗時の最大リトライ回数（デフォルト: 3）",
	"hooks.on_completion":                 "完了時に実行するコマンド（例: go test ./...）",
	"hooks.on_step_complete":              "ステップ完了時に実行するコマンド（Plan Mode用）",
	"hooks.timeout":                       "コマンドタイムアウト（秒）（デフォルト: 60）",
	"lsp.enabled":                         "LSP連携の有効/無効",
	"lsp.skip_install_prompt":             "インストール提案をスキップ",
	"mcp.enabled":                         "MCP接続を有効化（デフォルト: true）",
	"mcp.headless":                        "Headlessモードでも接続（デフォルト: false）",
	"openai.responses_api_models":         "Responses APIを使用するモデル",
	"output.assistant_updates":            "assistant prose の中間表示制御（verbose / phase / off、空でモード別デフォルト）",
	"output.max_lines":                    "折りたたみ前の最大表示行数",
	"paste.bracketed_paste":               "Bracketed Paste Mode を有効化（複数行ペースト対応）",
	"paste.max_bytes":                     "最大バイト数",
	"paste.max_lines":                     "最大行数",
	"paste.timeout_seconds":               "タイムアウト（秒）",
	"plan_mode.clear_context_on_approval": "Plan 承認後に調査フェーズの履歴をクリアして実装を開始",
	"plan_mode.max_retry":                 "最大リトライ回数",
	"plan_mode.step_timeout":              "ステップタイムアウト（秒）",
	"project_map.additional_ignore_dirs":  "追加除外ディレクトリ（list_dir と共通）",
	"project_map.context_ratio":           "ProjectMap のベース比率（0.01-0.20、デフォルト: 0.05。大規模 repo では 0.03-0.04 に自動補正）",
	"project_map.enabled":                 "セッション開始時にプロジェクト構造マップを生成・注入",
	"prompt_cache.cache_ttl":              "キャッシュTTL（デフォルト: 5m、1h で延長キャッシュ）",
	"prompt_cache.enabled":                "有効化（cache_control ブレークポイントを設定）",
	"provider_models":                     "プロバイダーごとのモデル設定",
	"streaming.idle_timeout_seconds":      "アイドルタイムアウト（秒）",
	"streaming.show_file_info":            "ファイル読み込み時にサイズ・行数を表示",
	"streaming.show_search_progress":      "検索時に進捗を表示",
	"streaming.stream_bash_output":        "bashコマンドの出力をリアルタイム表示",
	"streaming.thinking_timeout_seconds":  "thinking専用タイムアウト秒（text/FC未受信時）",
	"sub_agent.default_effort":            "既定推論強度（off / low / medium / high）",
	"sub_agent.default_model":             "既定モデル（空でメイン provider の最安モデルを自動選択）",
	"sub_agent.enabled":                   "サブエージェント機能を有効化",
	"sub_agent.max_concurrent":            "同時実行上限（デフォルト: 5）",
	"thinking.enabled":                    "有効化",
	"thinking.level":                      "レベル: low / medium / high / xhigh",
	"tool_confirm.auto_approve_medium":    "中程度のツール（write_file等）を自動承認",
	"tool_confirm.auto_approve_safe":      "安全なツール（read_file等）を自動承認",
	"utility_model.enabled":               "utility model を有効化",
	"utility_model.model":                 "補助タスク用モデル（空 = provider_models の default_model）",
	"utility_model.provider":              "補助タスク用プロバイダー（openai / gemini / claude など）",
	"utility_model.tasks":                 "許可する軽量タスク（例: web_search_compaction）",
	"web_search.cache_enabled":            "キャッシュを有効化（デフォルト: true）",
	"web_search.cache_size":               "最大キャッシュ数（デフォルト: 50）",
	"web_search.cache_ttl":                "キャッシュTTL秒数（デフォルト: 3600 = 1時間）",
	"web_search.provider":                 "検索プロバイダー（openai / gemini / claude、未設定時はメインプロバイダーを使用）",
}

// CategoryIcons はカテゴリのアイコン
var CategoryIcons = map[string]string{
	"bash":            "💻",
	"command_aliases": "🔗",
	"compression":     "📦",
	"general":         "⚙️",
	"git_stage":       "📂",
	"hooks":           "🏁",
	"lsp":             "🔧",
	"mcp":             "🔌",
	"openai":          "🌟",
	"output":          "📤",
	"paste":           "📋",
	"plan_mode":       "📋",
	"project_map":     "🗺️",
	"prompt_cache":    "💨",
	"provider":        "🤖",
	"streaming":       "📺",
	"sub_agent":       "🚀",
	"thinking":        "🧠",
	"tool_confirm":    "✅",
	"utility_model":   "🪶",
	"web_search":      "🔍",
}
