// Code generated by gen-config-registry.go. DO NOT EDIT.

package config

// ConfigFieldType はフィールドの型
type ConfigFieldType int

const (
	FieldTypeBool ConfigFieldType = iota
	FieldTypeInt
	FieldTypeString
	FieldTypeSelect      // 選択肢付き文字列
	FieldTypeFloat       // float64
	FieldTypeStringSlice // []string
	FieldTypeStringMap   // map[string]string
	FieldTypeStructMap   // map[string]struct
)

// CategoryDef はカテゴリ定義
type CategoryDef struct {
	Name        string   // カテゴリ名
	DisplayName string   // 表示名
	Icon        string   // アイコン
	Fields      []string // フィールドパス
}

// CategoryDefinitions はカテゴリ定義リスト
var CategoryDefinitions = []CategoryDef{
	{Name: "provider", DisplayName: "Provider & Model", Icon: "🤖", Fields: []string{"default_model", "default_provider", "provider_models"}},
	{Name: "compression", DisplayName: "Compression", Icon: "📦", Fields: []string{"compression.auto_compress", "compression.claude_compaction", "compression.clear_tool_inputs", "compression.clear_tool_uses", "compression.clear_tool_uses_trigger", "compression.compaction_trigger", "compression.keep_recent", "compression.model", "compression.prefer_compact_api", "compression.threshold_percent", "compression.threshold_tokens", "compression.token_threshold"}},
	{Name: "loop_detection", DisplayName: "Loop Detection", Icon: "🔄", Fields: []string{"loop_detection.threshold"}},
	{Name: "api_retry", DisplayName: "API Settings", Icon: "🌐", Fields: []string{"api_retry.count", "api_retry.initial_delay", "api_retry.max_delay", "api_retry.timeout"}},
	{Name: "diff", DisplayName: "Diff Display", Icon: "📝", Fields: []string{"diff.context_lines", "diff.max_total_lines"}},
	{Name: "tool_confirm", DisplayName: "Tool Confirm", Icon: "✅", Fields: []string{"tool_confirm.auto_approve_medium", "tool_confirm.auto_approve_safe"}},
	{Name: "command_aliases", DisplayName: "Command Aliases", Icon: "🔗", Fields: []string{"command_aliases"}},
	{Name: "prompt_cache", DisplayName: "Prompt Cache", Icon: "💨", Fields: []string{"prompt_cache.enabled"}},
	{Name: "paste", DisplayName: "Paste Mode", Icon: "📋", Fields: []string{"paste.bracketed_paste", "paste.max_bytes", "paste.max_lines", "paste.timeout_seconds"}},
	{Name: "streaming", DisplayName: "Streaming", Icon: "📺", Fields: []string{"streaming.idle_timeout_seconds", "streaming.show_file_info", "streaming.show_search_progress", "streaming.stream_bash_output"}},
	{Name: "bash", DisplayName: "Bash Safety", Icon: "💻", Fields: []string{"bash.allow_inline_edit", "bash.allow_pipe", "bash.allow_redirect", "bash.safe_commands", "bash.safety_level"}},
	{Name: "project_map", DisplayName: "Project Map", Icon: "🗺️", Fields: []string{"project_map.additional_ignore_dirs", "project_map.context_ratio", "project_map.enabled"}},
	{Name: "git_stage", DisplayName: "Git Settings", Icon: "📂", Fields: []string{"git_stage.batch_confirm"}},
	{Name: "plan_mode", DisplayName: "Plan Mode", Icon: "📋", Fields: []string{"plan_mode.clear_context_on_approval", "plan_mode.max_retry", "plan_mode.step_timeout"}},
	{Name: "lsp", DisplayName: "LSP Servers", Icon: "🔧", Fields: []string{"lsp.enabled", "lsp.skip_install_prompt"}},
	{Name: "openai", DisplayName: "OpenAI", Icon: "🌟", Fields: []string{"openai.responses_api_models"}},
	{Name: "thinking", DisplayName: "Thinking", Icon: "🧠", Fields: []string{"thinking.enabled", "thinking.level"}},
	{Name: "output", DisplayName: "Output", Icon: "📤", Fields: []string{"output.max_lines"}},
	{Name: "web_search", DisplayName: "Web Search", Icon: "🔍", Fields: []string{"web_search.cache_enabled", "web_search.cache_size", "web_search.cache_ttl", "web_search.provider"}},
	{Name: "mcp", DisplayName: "MCP Servers", Icon: "🔌", Fields: []string{"mcp.enabled", "mcp.headless"}},
	{Name: "hooks", DisplayName: "Hooks", Icon: "🏁", Fields: []string{"hooks.max_retry", "hooks.on_completion", "hooks.timeout"}},
}

// FieldTypeMap はフィールドパスから型へのマップ
var FieldTypeMap = map[string]ConfigFieldType{
	"api_retry.count":                     FieldTypeInt,
	"api_retry.initial_delay":             FieldTypeInt,
	"api_retry.max_delay":                 FieldTypeInt,
	"api_retry.timeout":                   FieldTypeInt,
	"bash.allow_inline_edit":              FieldTypeBool,
	"bash.allow_pipe":                     FieldTypeBool,
	"bash.allow_redirect":                 FieldTypeBool,
	"bash.safe_commands":                  FieldTypeStringSlice,
	"bash.safety_level":                   FieldTypeSelect,
	"command_aliases":                     FieldTypeStringMap,
	"compression.auto_compress":           FieldTypeBool,
	"compression.claude_compaction":       FieldTypeBool,
	"compression.clear_tool_inputs":       FieldTypeBool,
	"compression.clear_tool_uses":         FieldTypeBool,
	"compression.clear_tool_uses_trigger": FieldTypeInt,
	"compression.compaction_trigger":      FieldTypeInt,
	"compression.keep_recent":             FieldTypeInt,
	"compression.model":                   FieldTypeString,
	"compression.prefer_compact_api":      FieldTypeBool,
	"compression.threshold_percent":       FieldTypeInt,
	"compression.threshold_tokens":        FieldTypeInt,
	"compression.token_threshold":         FieldTypeInt,
	"default_model":                       FieldTypeString,
	"default_provider":                    FieldTypeSelect,
	"diff.context_lines":                  FieldTypeInt,
	"diff.max_total_lines":                FieldTypeInt,
	"general.clear_assistant_content":     FieldTypeBool,
	"general.language":                    FieldTypeSelect,
	"general.tool_loop_limit":             FieldTypeInt,
	"git_stage.batch_confirm":             FieldTypeBool,
	"hooks.max_retry":                     FieldTypeInt,
	"hooks.on_completion":                 FieldTypeStringSlice,
	"hooks.timeout":                       FieldTypeInt,
	"loop_detection.threshold":            FieldTypeInt,
	"lsp.enabled":                         FieldTypeBool,
	"lsp.servers":                         FieldTypeStructMap,
	"lsp.skip_install_prompt":             FieldTypeBool,
	"mcp.enabled":                         FieldTypeBool,
	"mcp.headless":                        FieldTypeBool,
	"openai.responses_api_models":         FieldTypeStringSlice,
	"output.max_lines":                    FieldTypeInt,
	"paste.bracketed_paste":               FieldTypeBool,
	"paste.max_bytes":                     FieldTypeInt,
	"paste.max_lines":                     FieldTypeInt,
	"paste.timeout_seconds":               FieldTypeInt,
	"plan_mode.clear_context_on_approval": FieldTypeBool,
	"plan_mode.max_retry":                 FieldTypeInt,
	"plan_mode.step_timeout":              FieldTypeInt,
	"project_map.additional_ignore_dirs":  FieldTypeStringSlice,
	"project_map.context_ratio":           FieldTypeFloat,
	"project_map.enabled":                 FieldTypeBool,
	"prompt_cache.enabled":                FieldTypeBool,
	"provider_models":                     FieldTypeStructMap,
	"streaming.idle_timeout_seconds":      FieldTypeInt,
	"streaming.show_file_info":            FieldTypeBool,
	"streaming.show_search_progress":      FieldTypeBool,
	"streaming.stream_bash_output":        FieldTypeBool,
	"thinking.enabled":                    FieldTypeBool,
	"thinking.level":                      FieldTypeSelect,
	"tool_confirm.auto_approve_medium":    FieldTypeBool,
	"tool_confirm.auto_approve_safe":      FieldTypeBool,
	"web_search.cache_enabled":            FieldTypeBool,
	"web_search.cache_size":               FieldTypeInt,
	"web_search.cache_ttl":                FieldTypeInt,
	"web_search.provider":                 FieldTypeSelect,
}

// SelectOptions は選択型フィールドの選択肢
var SelectOptions = map[string][]string{
	"bash.safety_level":   {"strict", "moderate", "permissive"},
	"default_provider":    {"deepseek", "claude", "openai", "gemini", "groq", "ollama", "openrouter", "bedrock"},
	"general.language":    {"ja", "en"},
	"thinking.level":      {"low", "medium", "high", "xhigh"},
	"web_search.provider": {"openai", "gemini", "claude"},
}

// FieldDescriptions はフィールドの説明
var FieldDescriptions = map[string]string{
	"api_retry.count":                     "リトライ回数",
	"api_retry.initial_delay":             "初回リトライ待機時間（秒）",
	"api_retry.max_delay":                 "最大待機時間（秒）",
	"api_retry.timeout":                   "タイムアウト（秒）",
	"bash.allow_inline_edit":              "インライン編集を許可（sed -i 等）",
	"bash.allow_pipe":                     "パイプを許可",
	"bash.allow_redirect":                 "リダイレクトを許可",
	"bash.safe_commands":                  "追加の安全コマンド（例: - \"npm run\"）",
	"bash.safety_level":                   "安全レベル: strict / moderate / permissive",
	"compression.auto_compress":           "トークン使用率が閾値を超えたら自動圧縮",
	"compression.claude_compaction":       "Claude系の compact_20260112 を有効化",
	"compression.clear_tool_inputs":       "tool_use 側の入力もクリアする",
	"compression.clear_tool_uses":         "Claude系の server-side tool clearing を有効化",
	"compression.clear_tool_uses_trigger": "clear_tool_uses のトリガー閾値（デフォルト: 80000）",
	"compression.compaction_trigger":      "compact のトリガー閾値（デフォルト: 150000）",
	"compression.keep_recent":             "圧縮時に保持する直近メッセージ数",
	"compression.model":                   "圧縮用モデル（空 = プロバイダー別デフォルト、main = メインモデル）",
	"compression.prefer_compact_api":      "プロバイダーのCompact APIを優先使用",
	"compression.threshold_percent":       "トークン使用率の閾値（%）",
	"compression.threshold_tokens":        "トークン数の閾値（0 = 使用しない）",
	"compression.token_threshold":         "絶対トークン閾値（デフォルト100000、キャッシュ有無に関係なく発動）",
	"default_model":                       "デフォルトで使用するモデル",
	"default_provider":                    "デフォルトで使用するLLMプロバイダー",
	"diff.context_lines":                  "差分表示時のコンテキスト行数",
	"diff.max_total_lines":                "差分表示の最大行数（0で無制限）",
	"general.clear_assistant_content":     "OpenAI / Gemini のツール呼び出し時 assistant 実況テキストを History から除去",
	"general.language":                    "表示言語（ja, en）",
	"general.tool_loop_limit":             "ツールループ最大回数（0で無制限）",
	"git_stage.batch_confirm":             "複数ファイルをまとめて確認",
	"hooks.max_retry":                     "フック失敗時の最大リトライ回数（デフォルト: 3）",
	"hooks.on_completion":                 "完了時に実行するコマンド（例: go test ./...）",
	"hooks.timeout":                       "コマンドタイムアウト（秒）（デフォルト: 60）",
	"loop_detection.threshold":            "同じツール呼び出しの繰り返し回数でループと判定",
	"lsp.enabled":                         "LSP連携の有効/無効",
	"lsp.skip_install_prompt":             "インストール提案をスキップ",
	"mcp.enabled":                         "MCP接続を有効化（デフォルト: true）",
	"mcp.headless":                        "Headlessモードでも接続（デフォルト: false）",
	"openai.responses_api_models":         "Responses APIを使用するモデル",
	"output.max_lines":                    "折りたたみ前の最大表示行数",
	"paste.bracketed_paste":               "Bracketed Paste Mode を有効化（複数行ペースト対応）",
	"paste.max_bytes":                     "最大バイト数",
	"paste.max_lines":                     "最大行数",
	"paste.timeout_seconds":               "タイムアウト（秒）",
	"plan_mode.clear_context_on_approval": "Plan 承認後に調査フェーズの履歴をクリアして実装を開始",
	"plan_mode.max_retry":                 "最大リトライ回数",
	"plan_mode.step_timeout":              "ステップタイムアウト（秒）",
	"project_map.additional_ignore_dirs":  "追加除外ディレクトリ（list_dir と共通）",
	"project_map.context_ratio":           "ProjectMap のベース比率（0.01-0.10、デフォルト: 0.02。大規模 repo では 0.03-0.04 に自動補正）",
	"project_map.enabled":                 "セッション開始時にプロジェクト構造マップを生成・注入",
	"prompt_cache.enabled":                "有効化（cache_control ブレークポイントを設定）",
	"provider_models":                     "プロバイダーごとのモデル設定",
	"streaming.idle_timeout_seconds":      "アイドルタイムアウト（秒）",
	"streaming.show_file_info":            "ファイル読み込み時にサイズ・行数を表示",
	"streaming.show_search_progress":      "検索時に進捗を表示",
	"streaming.stream_bash_output":        "bashコマンドの出力をリアルタイム表示",
	"thinking.enabled":                    "有効化",
	"thinking.level":                      "レベル: low / medium / high / xhigh",
	"tool_confirm.auto_approve_medium":    "中程度のツール（write_file等）を自動承認",
	"tool_confirm.auto_approve_safe":      "安全なツール（read_file等）を自動承認",
	"web_search.cache_enabled":            "キャッシュを有効化（デフォルト: true）",
	"web_search.cache_size":               "最大キャッシュ数（デフォルト: 50）",
	"web_search.cache_ttl":                "キャッシュTTL秒数（デフォルト: 3600 = 1時間）",
	"web_search.provider":                 "検索プロバイダー（openai / gemini / claude、未設定時はメインプロバイダーを使用）",
}

// CategoryIcons はカテゴリのアイコン
var CategoryIcons = map[string]string{
	"api_retry":       "🌐",
	"bash":            "💻",
	"command_aliases": "🔗",
	"compression":     "📦",
	"diff":            "📝",
	"git_stage":       "📂",
	"hooks":           "🏁",
	"loop_detection":  "🔄",
	"lsp":             "🔧",
	"mcp":             "🔌",
	"openai":          "🌟",
	"output":          "📤",
	"paste":           "📋",
	"plan_mode":       "📋",
	"project_map":     "🗺️",
	"prompt_cache":    "💨",
	"provider":        "🤖",
	"streaming":       "📺",
	"thinking":        "🧠",
	"tool_confirm":    "✅",
	"web_search":      "🔍",
}
