package commandcatalog

// Commands はコマンド一覧
var Commands = []CommandInfo{
	{
		Name:          "/exit",
		Aliases:       []string{"/quit", "/q"},
		Description:   "Exit the CLI",
		DescriptionJP: "CLIを終了",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategorySystem,
		Discoverable:  true,
		SortWeight:    900,
	},
	{
		Name:          "/clear",
		Description:   "Clear conversation history",
		DescriptionJP: "会話履歴をクリア",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategorySession,
		Discoverable:  true,
		SortWeight:    160,
	},
	{
		Name:          "/history",
		Description:   "Show conversation history",
		DescriptionJP: "会話履歴を表示",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategorySession,
		Discoverable:  true,
		SortWeight:    170,
	},
	{
		Name:          "/save",
		Description:   "Save current session",
		DescriptionJP: "セッションを保存",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategorySession,
		Discoverable:  true,
		SortWeight:    130,
	},
	{
		Name:          "/load",
		Args:          "[id]",
		Description:   "Load session (or last if no ID)",
		DescriptionJP: "セッションを読み込み",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategorySession,
		Discoverable:  true,
		SortWeight:    140,
	},
	{
		Name:          "/sessions",
		Description:   "List recent sessions",
		DescriptionJP: "最近のセッション一覧",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategorySession,
		Discoverable:  true,
		SortWeight:    150,
	},
	{
		Name:          "/status",
		Aliases:       []string{"/stats"},
		Description:   "Show current state, last request, and session statistics",
		DescriptionJP: "現在状態、直近リクエスト、セッション統計を表示",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategorySystem,
		Discoverable:  true,
		SortWeight:    50,
	},
	{
		Name:          "/tokens",
		Description:   "Show token usage and context window status",
		DescriptionJP: "トークン使用量を表示",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategoryContext,
		Discoverable:  true,
		SortWeight:    60,
	},
	{
		Name:          "/copy",
		Args:          "[code] [-n N]",
		Description:   "Copy last AI output to clipboard (code=code blocks only, -n=N-th last output)",
		DescriptionJP: "AI出力をクリップボードにコピー",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategorySession,
		Discoverable:  true,
		SortWeight:    100,
	},
	{
		Name:          "/review",
		Description:   "Review current changes and find issues",
		DescriptionJP: "現在の変更をレビュー",
		Surfaces:      []CommandSurface{CommandSurfaceTUI},
		Owner:         CommandOwnerTUIRouter,
		Lifecycle:     CommandLifecyclePreview,
		Category:      CommandCategoryReview,
		Discoverable:  true,
		SortWeight:    70,
	},
	{
		Name:          "/compress",
		Args:          "[N] [-c]",
		Description:   "Compress history (keep recent N, -c: use OpenAI Compact API)",
		DescriptionJP: "履歴を圧縮",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategoryContext,
		Discoverable:  true,
		SortWeight:    110,
	},
	{
		Name:          "/use",
		Args:          "<provider> [model]",
		Description:   "Switch provider and optionally model (e.g., /use gemini gemini-2.0-flash-exp)",
		DescriptionJP: "プロバイダーを切り替え",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategoryModel,
		Discoverable:  true,
		SortWeight:    20,
	},
	{
		Name:          "/providers",
		Description:   "List available providers and their API key status",
		DescriptionJP: "利用可能なプロバイダー一覧",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategoryModel,
		Discoverable:  true,
		SortWeight:    30,
	},
	{
		Name:          "/config",
		Description:   "Edit global config.yaml settings",
		DescriptionJP: "対話式設定変更",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategoryConfig,
		Discoverable:  true,
		SortWeight:    90,
		SubCommands: []SubCommand{
			{Name: "/config show", Description: "Show all settings with diff from defaults"},
			{Name: "/config model <name>", Description: "Change default model"},
		},
	},
	{
		Name:          "/skills",
		Description:   "List and inspect Agent Skills catalog",
		DescriptionJP: "Agent Skillsの一覧と診断",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategoryContext,
		Discoverable:  true,
		SortWeight:    95,
		SubCommands: []SubCommand{
			{Name: "/skills list", Description: "List discovered skills"},
			{Name: "/skills show <name>", Description: "Show SKILL.md body and resource listings"},
			{Name: "/skills doctor", Description: "Show parsing/duplicate diagnostics"},
		},
	},
	{
		Name:          "/model",
		Args:          "[name]",
		Description:   "Show current model or switch model without restart",
		DescriptionJP: "モデルを表示/切り替え",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategoryModel,
		Discoverable:  true,
		SortWeight:    10,
	},
	{
		Name:          "/init",
		Description:   "Create xelyon.yaml project template",
		DescriptionJP: "xelyon.yamlテンプレートを作成",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategoryConfig,
		Discoverable:  true,
		SortWeight:    180,
	},
	{
		Name:          "/project",
		Description:   "Edit project xelyon.yaml interactively",
		DescriptionJP: "xelyon.yamlを対話式で編集",
		Surfaces:      []CommandSurface{CommandSurfaceTUI},
		Owner:         CommandOwnerTUIRouter,
		Category:      CommandCategoryConfig,
		Discoverable:  true,
		SortWeight:    80,
	},
	{
		Name:          "/plan",
		Args:          "[on|off]",
		Description:   "Toggle Plan Mode (investigation -> plan -> approval; implementation happens on next normal turn)",
		DescriptionJP: "Plan Modeを切り替え",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategoryDev,
		Discoverable:  true,
		SortWeight:    120,
	},
	{
		Name:          "/think",
		Args:          "[on|off|level]",
		Description:   "Toggle Extended Thinking mode (level: low/medium/high/xhigh)",
		DescriptionJP: "Extended Thinkingを切り替え",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategoryModel,
		Discoverable:  true,
		SortWeight:    40,
	},
	{
		Name:          "/lsp",
		Args:          "[status]",
		Description:   "Show LSP server status (running/not started/disabled)",
		DescriptionJP: "LSPサーバー状態を表示",
		Surfaces:      classicOnlySurfaces(),
		Category:      CommandCategoryDev,
		SortWeight:    190,
	},
	{
		Name:          "/version",
		Description:   "Show version information",
		DescriptionJP: "バージョンを表示",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategorySystem,
		SortWeight:    920,
	},
	{
		Name:          "/help",
		Description:   "Show this help",
		DescriptionJP: "ヘルプを表示",
		Surfaces:      legacyFallbackSurfaces(),
		Category:      CommandCategorySystem,
		SortWeight:    910,
	},
}

// Tips はTips一覧
var Tips = []string{
	"Just describe what you want in natural language",
	"AI will ask confirmation for dangerous operations",
	"Use Ctrl+C to cancel current operation",
	"Use git to revert file changes when needed",
}
